const images = {
  logo: require("src/assets/images/boltLogo.png"),
  mainlogo: require("src/assets/images/lwlogo.png"),
  back: require("src/assets/images/back.png"),
  warn: require("src/assets/images/warn.png"),
  alertActive: require("src/assets/images/clockActive.png"),
  alert: require("src/assets/images/clockInactive.png"),
  notificationActive: require("src/assets/images/notificationsActive.png"),
  notification: require("src/assets/images/notificationsInactive.png"),
  profileActive: require("src/assets/images/profileActive.png"),
  profile: require("src/assets/images/profileInactive.png"),
  antenna: require("src/assets/images/antenna.png"),
  close: require("src/assets/images/close.png"),
  earningsIconGreen: require("src/assets/images/earningsIconGreen.png"),
  earningsIconRed: require("src/assets/images/earningsIconRed.png"),
  playIcon: require("src/assets/images/playIcon.png"),
  pauseIcon: require("src/assets/images/pauseIcon.png"),
  trashIcon: require("src/assets/images/trashIcon.png"),
  editIcon: require("src/assets/images/editIcon.png"),
  fireIcon: require("src/assets/images/fireIcon.png"),
  fire: require("src/assets/images/fire.png"),
  check: require("src/assets/images/check.png"),
  premiumIllustration: require("src/assets/images/premiumIllustration.png"),
  notesIcon: require("src/assets/images/notesIcon.png"),
  nomessages: require("src/assets/images/no_messages.png"),
  nomessageList: require("src/assets/images/hui.png"),
};
export default images;
